name: omnisense
description: A mobile app to assist visually impaired individuals by combining object detection, haptic feedback, and audio output. 

version: 1.0.0

environment:
   sdk:  ">=2.18.0  <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.0.2
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  
  assets:
  - assets/images/omnisense_logo.png
  
  